apiVersion: v1
kind: PersistentVolume

metadata:
  name: logs-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/data/logs"

---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: output-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/data/output"