apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: logs-pvc

spec:
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: output-pvc

spec:
  storageClassName: ""

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
