apiVersion: v1
kind: Service

metadata:
  name: malware-detector-service

spec:
  selector:
    app: malware-detector

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer